# Generated by Django 2.1 on 2018-12-21 09:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('town_1', 'town_2', 'user')},
        ),
    ]
