countries = {   "aruba":"AW",
                "afghanistan":"AF",
                "angola":"AO",
                "anguilla":"AI",
                "åland islands":"AX",
                "albania":"AL",
                "andorra":"AD",
                "united arab emirates":"AE",
                "argentina":"AR",
                "armenia":"AM",
                "american samoa":"AS",
                "antarctica":"AQ",
                "french southern territories":"TF",
                "antigua and barbuda":"AG",
                "australia":"AU",
                "austria":"AT",
                "azerbaijan":"AZ",
                "burundi":"BI",
                "belgium":"BE",
                "benin":"BJ",
                "bonaire, sint eustatius and saba":"BQ",
                "burkina faso":"BF",
                "bangladesh":"BD",
                "bulgaria":"BG",
                "bahrain":"BH",
                "bahamas":"BS",
                "bosnia and herzegovina":"BA",
                "saint barthélemy":"BL",
                "belarus":"BY",
                "belize":"BZ",
                "bermuda":"BM",
                "bolivia, plurinational state of":"BO",
                "brazil":"BR",
                "barbados":"BB",
                "brunei darussalam":"BN",
                "bhutan":"BT",
                "bouvet island":"BV",
                "botswana":"BW",
                "central african republic":"CF",
                "canada":"CA",
                "cocos (keeling) islands":"CC",
                "switzerland":"CH",
                "chile":"CL",
                "china":"CN",
                "côte d'ivoire":"CI",
                "cameroon":"CM",
                "congo, the democratic republic of the":"CD",
                "congo":"CG",
                "cook islands":"CK",
                "colombia":"CO",
                "comoros":"KM",
                "cabo verde":"CV",
                "costa rica":"CR",
                "cuba":"CU",
                "curaçao":"CW",
                "christmas island":"CX",
                "cayman islands":"KY",
                "cyprus":"CY",
                "czechia":"CZ",
                "germany":"DE",
                "djibouti":"DJ",
                "dominica":"DM",
                "denmark":"DK",
                "dominican republic":"DO",
                "algeria":"DZ",
                "ecuador":"EC",
                "egypt":"EG",
                "eritrea":"ER",
                "western sahara":"EH",
                "spain":"ES",
                "estonia":"EE",
                "ethiopia":"ET",
                "finland":"FI",
                "fiji":"FJ",
                "falkland islands (malvinas)":"FK",
                "france":"FR",
                "faroe islands":"FO",
                "micronesia, federated states of":"FM",
                "gabon":"GA",
                "united kingdom":"GB",
                "georgia":"GE",
                "guernsey":"GG",
                "ghana":"GH",
                "gibraltar":"GI",
                "guinea":"GN",
                "guadeloupe":"GP",
                "gambia":"GM",
                "guinea-bissau":"GW",
                "equatorial guinea":"GQ",
                "greece":"GR",
                "grenada":"GD",
                "greenland":"GL",
                "guatemala":"GT",
                "french guiana":"GF",
                "guam":"GU",
                "guyana":"GY",
                "hong kong":"HK",
                "heard island and mcdonald islands":"HM",
                "honduras":"HN",
                "croatia":"HR",
                "haiti":"HT",
                "hungary":"HU",
                "indonesia":"ID",
                "isle of man":"IM",
                "india":"IN",
                "british indian ocean territory":"IO",
                "ireland":"IE",
                "iran, islamic republic of":"IR",
                "iraq":"IQ",
                "iceland":"IS",
                "israel":"IL",
                "italy":"IT",
                "jamaica":"JM",
                "jersey":"JE",
                "jordan":"JO",
                "japan":"JP",
                "kazakhstan":"KZ",
                "kenya":"KE",
                "kyrgyzstan":"KG",
                "cambodia":"KH",
                "kiribati":"KI",
                "saint kitts and nevis":"KN",
                "korea, republic of":"KR",
                "kuwait":"KW",
                "lao people's democratic republic":"LA",
                "lebanon":"LB",
                "liberia":"LR",
                "libya":"LY",
                "saint lucia":"LC",
                "liechtenstein":"LI",
                "sri lanka":"LK",
                "lesotho":"LS",
                "lithuania":"LT",
                "luxembourg":"LU",
                "latvia":"LV",
                "macao":"MO",
                "saint martin (french part)":"MF",
                "morocco":"MA",
                "monaco":"MC",
                "moldova, republic of":"MD",
                "madagascar":"MG",
                "maldives":"MV",
                "mexico":"MX",
                "marshall islands":"MH",
                "macedonia, republic of":"MK",
                "mali":"ML",
                "malta":"MT",
                "myanmar":"MM",
                "montenegro":"ME",
                "mongolia":"MN",
                "northern mariana islands":"MP",
                "mozambique":"MZ",
                "mauritania":"MR",
                "montserrat":"MS",
                "martinique":"MQ",
                "mauritius":"MU",
                "malawi":"MW",
                "malaysia":"MY",
                "mayotte":"YT",
                "namibia":"NA",
                "new caledonia":"NC",
                "niger":"NE",
                "norfolk island":"NF",
                "nigeria":"NG",
                "nicaragua":"NI",
                "niue":"NU",
                "netherlands":"NL",
                "norway":"NO",
                "nepal":"NP",
                "nauru":"NR",
                "new zealand":"NZ",
                "oman":"OM",
                "pakistan":"PK",
                "panama":"PA",
                "pitcairn":"PN",
                "peru":"PE",
                "philippines":"PH",
                "palau":"PW",
                "papua new guinea":"PG",
                "poland":"PL",
                "puerto rico":"PR",
                "korea, democratic people's republic of":"KP",
                "portugal":"PT",
                "paraguay":"PY",
                "palestine, state of":"PS",
                "french polynesia":"PF",
                "qatar":"QA",
                "réunion":"RE",
                "romania":"RO",
                "russia":"RU",
                "rwanda":"RW",
                "saudi arabia":"SA",
                "sudan":"SD",
                "senegal":"SN",
                "singapore":"SG",
                "south georgia and the south sandwich islands":"GS",
                "saint helena, ascension and tristan da cunha":"SH",
                "svalbard and jan mayen":"SJ",
                "solomon islands":"SB",
                "sierra leone":"SL",
                "el salvador":"SV",
                "san marino":"SM",
                "somalia":"SO",
                "saint pierre and miquelon":"PM",
                "serbia":"RS",
                "south sudan":"SS",
                "sao tome and principe":"ST",
                "suriname":"SR",
                "slovakia":"SK",
                "slovenia":"SI",
                "sweden":"SE",
                "swaziland":"SZ",
                "sint maarten (dutch part)":"SX",
                "seychelles":"SC",
                "syrian arab republic":"SY",
                "turks and caicos islands":"TC",
                "chad":"TD",
                "togo":"TG",
                "thailand":"TH",
                "tajikistan":"TJ",
                "tokelau":"TK",
                "turkmenistan":"TM",
                "timor-leste":"TL",
                "tonga":"TO",
                "trinidad and tobago":"TT",
                "tunisia":"TN",
                "turkey":"TR",
                "tuvalu":"TV",
                "taiwan, province of china":"TW",
                "tanzania, united republic of":"TZ",
                "uganda":"UG",
                "ukraine":"UA",
                "united states minor outlying islands":"UM",
                "uruguay":"UY",
                "united states":"US",
                "uzbekistan":"UZ",
                "holy see (vatican city state)":"VA",
                "saint vincent and the grenadines":"VC",
                "venezuela, bolivarian republic of":"VE",
                "virgin islands, british":"VG",
                "virgin islands, u.s.":"VI",
                "viet nam":"VN",
                "vanuatu":"VU",
                "wallis and futuna":"WF",
                "samoa":"WS",
                "yemen":"YE",
                "south africa":"ZA",
                "zambia":"ZM",
                "zimbabwe":"ZW",
            }